# -*- coding: utf-8 -*-
"""Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-aPodytNKWas4UxlKkwjvy1SRiTgc4G

### **Import Libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dropout

"""### **Load And Explore**"""

# 1 - Load the dataset
df = pd.read_csv("/content/AI_Human.csv",engine="python",on_bad_lines="skip")
df.to_csv("/content/sample_data/AI_Human_clean.csv", index=False)

# We used this approach to handle and clean formatting issues in the dataset
# so it can be loaded correctly without parsing errors or inconsistent row structures.

# 2 - Print the first 5 rows
display('first 5 rows:',df.head())

# 3 - Check the shape
print('\nCheck the shape:',df.shape)

# 4 - Check for missing values
print('\nCheck for missing values:',df.isnull().sum())

# 5 - Check class balance
print('\nCheck class balance:',df['generated'].value_counts())
# 0.0 Human
# 1.0 Ai

# The dataset is imbalanced because one class contains more samples than the other.
# So, F1-score was used as the primary evaluation metric instead of accuracy.

"""### **Prepare the Data**"""

from sklearn.model_selection import train_test_split
# 1 - Identify the axes
X = df['text']
y = df['generated']

# 2 - Dividing the data set into train and test
X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.5, random_state=42, stratify=y
)

"""
Text datasets only: clean the text
"""
import re, nltk
from nltk.corpus import stopwords
# 1 - Download English stop words
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# 2 - Cleaning function
def clean(text):
 text = text.lower()# Converting text to lowercase letters
 text = re.sub(r'[^a-z\s]', '', text) # Delete any non-English character or distance
 words = [w for w in text.split() if w not in stop_words]
 return ' '.join(words)

#  3 - Applying the cleaning function to the data set
df['clean_text'] = df['text'].apply(clean)

"""
Convert text to numbers with TF-IDF
"""
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000) # 1 - Create a tfidf
X_train = tfidf.fit_transform(X_train) # 2 - Learn vocab on train only and convert training data into numbers
X_test = tfidf.transform(X_test) # 3 - apply to test convert training data into numbers

"""### **Train and Compare Models**

Logistic Regression Model
"""

# Train the Logistic Regression Model
model1=LogisticRegression()
model1.fit(X_train,y_train)

# Logistic Regression Model Prediction
logis_pred=model1.predict(X_test)

"""Random Forest Model"""

# Train the Random Forest Model
model2=RandomForestClassifier()
model2.fit(X_train,y_train)

# Random Forest Model Prediction
rndm_pred=model2.predict(X_test)

"""KNN Model"""

# Train the KNN Model
model3=KNeighborsClassifier()
model3.fit(X_train,y_train)

# KNN Model Prediction
knn_pred=model3.predict(X_test)

"""Accuracy"""

print('Logistic Regression Accuracy:',accuracy_score(y_test,logis_pred))
print('\nRandom Forest Accuracy:',accuracy_score(y_test,rndm_pred))
print('\nKNN Accuracy:',accuracy_score(y_test,knn_pred))

"""Precision"""

print('Logistic Regression Precision:',precision_score(y_test,logis_pred))
print('\nRandom Forest Precision:',precision_score(y_test,rndm_pred))
print('\nKNN Precision:',precision_score(y_test,knn_pred))

"""Recall"""

print('Logistic Regression Recall:',recall_score(y_test,logis_pred))
print('\nRandom Forest Recall:',recall_score(y_test,rndm_pred))
print('\nKNN Recall:',recall_score(y_test,knn_pred))

"""F1-score"""

print('Logistic Regression F1-score:',f1_score(y_test,logis_pred))
print('\nRandom Forest F1-score:',f1_score(y_test,rndm_pred))
print('\nKNN F1-score:',f1_score(y_test,knn_pred))

"""### **Plot A Confusion Matrix For Each Model**"""

cm1=confusion_matrix(y_test,logis_pred)
cm2=confusion_matrix(y_test,rndm_pred)
cm3=confusion_matrix(y_test,knn_pred)

"""The cmap colors used in this heatmap were inspired by
https://matplotlib.org/stable/users/explain/colors/colormaps.html
"""

plt.figure(figsize=(8,6))
sns.heatmap(cm1,annot=True,cmap='RdPu')
plt.title('Logistic Regression Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show

plt.figure(figsize=(8,6))
sns.heatmap(cm2,annot=True,cmap='PuRd')
plt.title('Random Forest Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show

plt.figure(figsize=(8,6))
sns.heatmap(cm3,annot=True,cmap='BuPu')
plt.title('KNN Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show

results = [
    {
        "Model": "Logistic Regression",
        "Accuracy": 0.9981998199819982,
        "Precision": 1.0,
        "Recall": 0.9952718676122931,
        "F1-score": 0.9976303317535545
    },
    {
        "Model": "Random Forest",
        "Accuracy": 0.9981998199819982,
        "Precision": 1.0,
        "Recall": 0.9952718676122931,
        "F1-score": 0.9976303317535545
    },
    {
        "Model": "KNN",
        "Accuracy":  0.9837983798379838,
        "Precision": 0.9633867276887872,
        "Recall": 0.9952718676122931,
        "F1-score": 0.9790697674418605
    }
]
results_df = pd.DataFrame(results)
print(f"results_df\n{results_df}")

The_best_model = results_df.loc[results_df["F1-score"].idxmax()]

print(f"The_Best Model:{The_best_model["Model"]}")

"""### **Neural Network**"""

"""first Neural Network"""
model_1 = Sequential([
    Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
    Dense(1, activation="sigmoid"), # One neuron for binary classification
])

#  1 - Assembly of the first model
model_1.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

#  2 - Training the first model using the original training data
history_1 = model_1.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

"""second Neural Network"""

# 1 - Convert labels to One-Hot Encoding
# Because neural networks calculate that 1 and 0 have a order, we did One-Hot Encoding
y_train_oh = to_categorical(y_train, num_classes=2)
y_test_oh = to_categorical(y_test, num_classes=2)

model_2 = Sequential([
    Dense(32, activation="relu", input_shape=(X_train.shape[1],)),
    Dropout(0.3), # Arrest30% to reduce overfitting
    Dense(2, activation="softmax"), # two neuron for categorical_crossentropy
])

# 2 - Assembly of the second model
model_2.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

#  3 - Training the first model using the original training data
history_2 = model_2.fit(X_train, y_train_oh, epochs=10, validation_data=(X_test, y_test_oh))

"""### **Plot the training vs. validation loss and accuracy curves**

The training loss and validation loss both decreased and stayed very close together, which means the model learned well and there are no clear signs of overfitting.
"""

plt.figure(figsize=(8,6))
plt.plot(history_1.history['loss'])
plt.plot(history_1.history['val_loss'])
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Model 1 Loss')

plt.figure(figsize=(8,6))
plt.plot(history_2.history['loss'])
plt.plot(history_2.history['val_loss'])
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Model 2 Loss')

"""The training accuracy and validation accuracy reached very high values and remained close together, indicating that the model performed consistently on both training and validation data."""

plt.figure(figsize=(8,6))
plt.plot(history_1.history['accuracy'])
plt.plot(history_1.history['val_accuracy'])
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Model 1 Accuracy')

plt.figure(figsize=(8,6))
plt.plot(history_2.history['accuracy'])
plt.plot(history_2.history['val_accuracy'])
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Model 2 Accuracy')

"""### **Evaluate the neural network using the same metrics as Step 1**"""

nn1_pred=model_1.predict(X_test)

nn2_pred=model_2.predict(X_test)

nn1_pred_binary=(nn1_pred>0.5).astype(int)
# We used (nn_pred > 0.5).astype(int) to convert the model’s probability outputs (from sigmoid) into final binary classes (0 or 1),
# because the confusion matrix requires discrete predictions instead of probabilities.
print('Neural Network Accuracy:',round(accuracy_score(y_test,nn1_pred_binary),2))
print('\nNeural Network Precision:',round(precision_score(y_test,nn1_pred_binary),2))
print('\nNeural Network Recall:',round(recall_score(y_test,nn1_pred_binary),2))
print('\nNeural Network F1-score:',round(f1_score(y_test,nn1_pred_binary),2))

nn2_pred_binary=np.argmax(nn2_pred, axis=1)
# We used `np.argmax(nn2_pred, axis=1)` to convert the model’s softmax probability outputs into final class labels
# by selecting the index of the highest probability for each sample, since evaluation metrics require discrete predictions instead of probability distributions.

print('Neural Network Accuracy:',round(accuracy_score(y_test,nn2_pred_binary),2))
print('\nNeural Network Precision:',round(precision_score(y_test,nn2_pred_binary),2))
print('\nNeural Network Recall:',round(recall_score(y_test,nn2_pred_binary),2))
print('\nNeural Network F1-score:',round(f1_score(y_test,nn2_pred_binary),2))

"""### **Add neural network results to the Step 1 summary table.**"""

results.append({
    "Model": "Neural Network 1",
    "Accuracy": 1.0,
    "Precision": 1.0,
    "Recall": 1.0,
    "F1-score": 1.0
})
results.append({
    "Model": "Neural Network 2",
    "Accuracy": 1.0,
    "Precision": 1.0,
    "Recall": 1.0,
    "F1-score": 1.0
})
results

"""### **Comparison Between Neural Network and Machine Learning Models.**


*   The neural network made fewer classification errors compared to the machine learning models.
*   The neural network model is far superior to all traditional machine learning models, achieving a perfect score of 100% across all metrics.
"""